allowBuilds:
  cpu-features: true
  eslint-plugin-n8n-nodes-base: true
  isolated-vm: true
  ssh2: true
  unrs-resolver: true
overrides:
  '@n8n/scan-community-package>typescript': 'npm:@typescript/typescript6@6.0.2'
  typescript: 5.9.3
  tmp: 0.2.7
  nanoid: 3.3.18
  qs: 6.16.0
